### ISSUE TITLE
Changing visible variable does not automatically trigger Dialog

### ISSUE THREAD

**Issue by r4j4h** [RiotGear/rg-modal#1]
One must trigger an update or use a reference to the tag to do the update.

After following instructions and adding the DOM and defining a js variable (globals work fine for this case):

```javascript
var a = riot.mount('rg-modal'); //Mounts fine
modal.visible = true; //Dialog does not show
a[0].update(); // Dialog shows
```

[Tag .update Documentation](https://muut.com/riotjs/api/#tag-update)

Alternatively, but not suggested to use, re-mounting also works by causing it to re-read things.
```javascript
riot.mount('rg-modal'); //Mounts fine
modal.visible = true; //Dialog does not show
riot.mount('rg-modal'); // Dialog shows
```

Note I did this by adding the elements to the page through Chrome's Inspector and by adding it to DOM to test if browser behaved differently if the objects were there from the start. Works the same both ways.

Am I missing something? If not, I think the documentation should be updated to mention that a triggering must occur after the variable is changed, as otherwise Riot does not re-render views. I wouldn't go into a specific way though since there's many ways to mount things, I think just a mention would be enough to help people. :)

Great work by the way!! :)

**Comment by gregorypratt** [comment]
Yep, good point. I didn't add any Riot specific documentation as I was assuming (rightly or wrongly) that people would just automatically call `update()` as and when they want to see the page...."update"

Thanks for the feedback!

**Comment by r4j4h** [comment]
No problem :) Thanks for the quick response!
