### ISSUE TITLE
Can you add bower?

### ISSUE THREAD

**Issue by LAKnoKAL** [RiotGear/rg-modal#8]

**Comment by gregorypratt** [comment]
Before I go ahead and do that could you explain why NPM doesn't work for you?

Thanks!

**Comment by LAKnoKAL** [comment]
No any problems with NPM, I just want to use bower for little libraries or packages like this... But i think you are right... no need bower here... because riot installing using npm so packages better to install using npm too... Sorry close it

**Comment by LAKnoKAL** [comment]
Good thoughts come during the discussion

**Comment by gregorypratt** [comment]
Nested dependencies (NPM) vs user dependency resolution (Bower) is the usual deciding factor but as you've pointed out you're using NPM already so...

Self closing issues are my favourite! 😃

**Comment by LAKnoKAL** [comment]
Nope, I use only bower in my current project, but I will use npm too ;)
